### ISSUE TITLE
Does FE only listen on ipv6?

### ISSUE THREAD

**Issue by onewayforever** [cornelisnetworks/opa-fm#7]
I can not connect to FE using FM GUI in Centos7. 
(I have already checked security setting closed.)

I found the fe only listen on tcp6, not tcp, below is the netstat output

tcp6       0      0 :::3245                 :::*                    LISTEN      3392/fe

but the FM GUI only support ipv4 address.

This may be the reason

Any one meet this problem ?

**Comment by sjb017** [comment]
Hello,

Thank you for your inquiry. The FE and FM GUI do support IPv4.

In order to help diagnose the situation, we recommend the following actions.


1)      Check whether the FE is configured properly
You can use the “opafequery” tool from the 01org/opa-ff repository to do this. This tool is an easy way to diagnose the connectivity to the FE without using the FM GUI. You can run the tool on the same server as the FM (and FE) is running

2)      Check that the network is configured properly
If the opafequery test in step (1) works properly, then there are issues with the network connectivity.
a) Check the firewall to ensure that the FE port is reachable
b) If step (a) passes, then the issue may be more complicated.
  1) If you are using both ipv4 and ipv6, let’s try to focus on ipv4 only
  2) If you are using only ipv6, you might try looking at the Java system property “java.net.preferIPv4Stack” and see if it is set to “true”. Check on the machine running the FM GUI first, look at JAVA_TOOL_OPTIONS or _JAVA_OPTIONS settings. If not, perhaps your organizaton is enforcing this policy, perhaps you can work with your system or network administrator.

3)      If you have verified that the FM GUI machine can communicate with the FE port, then we would ask that you send us the fmgui log file. If you wish to avoid publishing such a log file in a public forum as this, let us know can you can send it to us privately.

We usually diagnose problems such as this to be firewall problems.

Thank you,
Scott Breyer
Maintainer, 01org/opa-fm
